[project]
name = "openai-agents-demos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai-agents[litellm]>=0.4.2",
    "fastapi>=0.115.0",
    "httpx>=0.27.0",
    "uvicorn>=0.32.0",
]
